spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
#配置数据源

  datasource:
     url: jdbc:mysql://10.18.93.13:3308/myutilproject0?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
     username: root
     password: jackdking@1234
     driver-class-name: com.mysql.jdbc.Driver
#mapper文件和mybatis全局配置文件
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml